return {
  inject: ['timer'],
  apply(ctx) {
    const slots = ctx.get('slots')
    if (slots === undefined) return
    let state = { loading: true, data: null, route: 'home', projectId: null, meetingId: null, candidate: '', recording: false, uploading: false, awaiting: false, error: null }
    const listeners = new Set()
    let serial = 0
    function emit(patch) { state = Object.assign({}, state, patch); listeners.forEach(function (fn) { try { fn() } catch (error) {} }) }
    function subscribe(fn) { listeners.add(fn); return function () { listeners.delete(fn) } }
    function useStateStore() { const pair = React.useState(state); React.useEffect(function () { return subscribe(function () { pair[1](state) }) }, []); return pair[0] }
    function command(type, payload, expectedVersion) { serial += 1; const request = { idempotencyKey: 'dynamic-ui:' + serial, type: type, payload: payload }; if (expectedVersion !== undefined) request.expectedVersion = expectedVersion; return host.call('command', request).then(refresh) }
    function refresh() { return host.call('snapshot', {}).then(function (data) { emit({ loading: false, data: data, error: null }); return data }, function (error) { emit({ loading: false, error: String(error && error.message || error) }); throw error }) }
    refresh()
    styles.insert('.fbd{height:100%;min-height:620px;display:grid;grid-template-columns:220px 1fr;background:var(--dsw-alias-bg-base,#fff);color:var(--dsw-alias-label-primary,#202124);font:13px/1.45 system-ui;letter-spacing:0}.fbd-side{overflow:auto;border-right:1px solid var(--dsw-alias-border-l2,#e4e5e7);background:var(--dsw-alias-bg-layer-1,#f7f7f8);padding:12px 8px}.fbd-brand{padding:4px 8px 14px;font-size:16px;font-weight:700}.fbd-side button{width:100%;border:0;border-radius:5px;padding:7px 9px;background:transparent;color:var(--dsw-alias-label-secondary,#65676d);text-align:left;cursor:pointer}.fbd-side button:hover,.fbd-side button[data-on=true]{background:var(--dsw-alias-interactive-bg-active,rgba(30,35,45,.1));color:inherit}.fbd-project{margin:5px 0 10px;padding-left:8px}.fbd-project small{display:block;padding:6px 8px 3px;color:var(--dsw-alias-label-caption,#898c93)}.fbd-main{min-width:0;overflow:auto;padding:24px}.fbd-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:20px}.fbd-head h2{margin:0;font-size:20px}.fbd-primary{border:0;border-radius:5px;padding:8px 12px;background:var(--dsw-alias-state-business-primary,#4d6bfe);color:#fff;cursor:pointer}.fbd-metrics{display:grid;grid-template-columns:repeat(4,1fr);border-block:1px solid var(--dsw-alias-border-l2,#e4e5e7)}.fbd-metrics div{padding:18px;border-right:1px solid var(--dsw-alias-border-l2,#e4e5e7)}.fbd-metrics strong{display:block;font-size:24px}.fbd-list{margin-top:22px;border-top:1px solid var(--dsw-alias-border-l2,#e4e5e7)}.fbd-row{display:grid;grid-template-columns:1fr auto;gap:10px;padding:12px 4px;border-bottom:1px solid var(--dsw-alias-border-l2,#e4e5e7)}.fbd-row span{color:var(--dsw-alias-label-caption,#898c93)}.fbd-board{display:flex;gap:10px;overflow:auto}.fbd-col{flex:0 0 260px;padding:10px;border:1px solid var(--dsw-alias-border-l2,#e4e5e7);border-radius:6px;background:var(--dsw-alias-bg-layer-1,#f7f7f8)}.fbd-card{margin-top:8px;padding:10px;border:1px solid var(--dsw-alias-border-l2,#e4e5e7);border-radius:5px;background:var(--dsw-alias-bg-base,#fff)}.fbd-dock{display:grid;grid-template-columns:auto auto 1fr auto;align-items:center;gap:8px;padding:7px 10px;border:1px solid var(--dsw-alias-border-l2,#e4e5e7);border-radius:6px;background:var(--dsw-alias-bg-base,#fff);font-size:11px}.fbd-live{color:var(--dsw-alias-state-success-primary,#2b8a5a);font-weight:700}.fbd-draft{overflow:hidden;color:var(--dsw-alias-label-caption,#898c93);text-overflow:ellipsis;white-space:nowrap}@media(max-width:700px){.fbd{grid-template-columns:1fr;grid-template-rows:150px 1fr}.fbd-side{border-right:0;border-bottom:1px solid var(--dsw-alias-border-l2,#e4e5e7)}.fbd-metrics{grid-template-columns:repeat(2,1fr)}}')
    function el(type, props) { const children = Array.prototype.slice.call(arguments, 2); return React.createElement.apply(React, [type, props || null].concat(children)) }
    function startMeeting(meeting) { return command('meeting.update', { id: meeting.id, status: 'live' }, meeting.version).then(function (data) { const live = data.meetings.find(function (item) { return item.id === meeting.id }); emit({ meetingId: meeting.id, route: 'meetings', recording: true }); return live }) }
    function App() {
      const current = useStateStore(); const data = current.data
      if (!data) return el('div', { className: 'fbd-main' }, current.error || '正在连接 Flowboard')
      const project = data.projects.find(function (item) { return item.id === current.projectId })
      let body
      if (current.route === 'home') body = el(React.Fragment, null, el('div', { className: 'fbd-head' }, el('h2', null, '工作空间'), el('button', { className: 'fbd-primary', onClick: function () { const first = data.meetings.find(function (item) { return item.status === 'scheduled' }); if (first) startMeeting(first) } }, '开始 AI 会议')), el('div', { className: 'fbd-metrics' }, el('div', null, '项目', el('strong', null, data.projects.length)), el('div', null, '任务', el('strong', null, data.tasks.length)), el('div', null, '会议', el('strong', null, data.meetings.length)), el('div', null, '资料', el('strong', null, data.library.length))))
      else if (current.route === 'board' && project) body = el(React.Fragment, null, el('div', { className: 'fbd-head' }, el('h2', null, project.name + ' · 看板')), el('div', { className: 'fbd-board' }, data.workflowStatuses.filter(function (status) { return status.projectId === project.id }).map(function (status) { return el('section', { className: 'fbd-col', key: status.id }, el('strong', null, status.name), data.tasks.filter(function (task) { return task.projectId === project.id && task.statusId === status.id }).map(function (task) { return el('article', { className: 'fbd-card', key: task.id }, el('strong', null, task.title), el('div', null, task.summary)) })) })))
      else { const list = current.route === 'meetings' ? data.meetings : current.route === 'library' ? data.library : data.tasks; body = el(React.Fragment, null, el('div', { className: 'fbd-head' }, el('h2', null, current.route === 'meetings' ? '会议' : current.route === 'library' ? '资料' : '我的任务')), el('div', { className: 'fbd-list' }, list.map(function (item) { return el('div', { className: 'fbd-row', key: item.id }, el('strong', null, item.title), el('span', null, item.status || item.type || '')) }))) }
      return el('div', { className: 'fbd' }, el('aside', { className: 'fbd-side' }, el('div', { className: 'fbd-brand' }, 'Flowboard'), el('button', { 'data-on': current.route === 'home', onClick: function () { emit({ route: 'home' }) } }, '首页'), el('div', { className: 'fbd-project' }, el('small', null, '项目'), data.projects.map(function (item) { return el('button', { key: item.id, 'data-on': current.projectId === item.id && current.route === 'board', onClick: function () { emit({ route: 'board', projectId: item.id }) } }, item.name + ' · 看板') })), el('button', { 'data-on': current.route === 'meetings', onClick: function () { emit({ route: 'meetings' }) } }, '会议'), el('button', { 'data-on': current.route === 'library', onClick: function () { emit({ route: 'library' }) } }, '资料'), el('button', { 'data-on': current.route === 'tasks', onClick: function () { emit({ route: 'tasks' }) } }, '我的任务')), el('main', { className: 'fbd-main' }, body))
    }
    function blob64(blob) { return new Promise(function (resolve, reject) { const reader = new FileReader(); reader.onload = function () { resolve(String(reader.result || '').split(',')[1] || '') }; reader.onerror = reject; reader.readAsDataURL(blob) }) }
    let media = null; let analyser = null; let recorder = null; let chunks = []; let vadCancel = null; let speechAt = 0; let inputActions = null; let silenceCancel = null
    function stopRecorder() { if (recorder && recorder.state !== 'inactive') recorder.stop() }
    async function beginAudio() { if (media) return; media = await navigator.mediaDevices.getUserMedia({ audio: true }); const audio = new AudioContext(); const source = audio.createMediaStreamSource(media); analyser = audio.createAnalyser(); analyser.fftSize = 2048; source.connect(analyser); const samples = new Uint8Array(analyser.fftSize); vadCancel = ctx.timer.interval(function () { analyser.getByteTimeDomainData(samples); let sum = 0; for (let i = 0; i < samples.length; i++) { const value = (samples[i] - 128) / 128; sum += value * value } const rms = Math.sqrt(sum / samples.length); const now = Date.now(); if (rms > 0.018) { speechAt = now; if (!recorder) { chunks = []; recorder = new MediaRecorder(media); recorder.ondataavailable = function (event) { if (event.data.size) chunks.push(event.data) }; recorder.onstop = async function () { const current = recorder; recorder = null; const blob = new Blob(chunks, { type: current.mimeType || 'audio/webm' }); emit({ uploading: true }); try { const text = (await host.call('transcribeSegment', { meetingId: state.meetingId, clientSegmentId: 'dyn-' + Date.now(), contentType: blob.type, base64: await blob64(blob), startedAt: new Date(now - 1000).toISOString(), endedAt: new Date().toISOString() })).text; if (text) { const candidate = state.candidate ? state.candidate + '\n' + text : text; emit({ candidate: candidate, awaiting: false }); if (inputActions) inputActions.setDraft(candidate); if (silenceCancel) silenceCancel(); silenceCancel = ctx.timer.timeout(function () { if (inputActions && state.candidate) { emit({ awaiting: true }); inputActions.submit() } }, 4000) } } catch (error) { emit({ error: String(error && error.message || error) }) } finally { emit({ uploading: false }) } }; recorder.start() } } else if (recorder && now - speechAt > 800) stopRecorder() }, 100) }
    function Dock(props) { const current = useStateStore(); inputActions = props.inputActions; React.useEffect(function () { if (current.meetingId && current.recording) beginAudio().catch(function (error) { emit({ error: String(error && error.message || error) }) }); return function () {} }, [current.meetingId, current.recording]); React.useEffect(function () { if (current.awaiting && props.input.draft === '' && props.input.phase === 'plain') emit({ candidate: '', awaiting: false }) }, [current.awaiting, props.input.draft, props.input.phase]); if (!current.meetingId) return null; return el('div', { className: 'fbd-dock' }, el('span', { className: 'fbd-live' }, current.recording ? 'AI 秘书在线' : '会议整理中'), el('strong', null, current.uploading ? '正在转写' : '实时转录'), el('span', { className: 'fbd-draft' }, current.candidate || '转录内容将在输入框待命'), el('button', { onClick: function () { const meeting = current.data.meetings.find(function (item) { return item.id === current.meetingId }); stopRecorder(); if (vadCancel) vadCancel(); if (media) media.getTracks().forEach(function (track) { track.stop() }); media = null; emit({ recording: false }); if (meeting) command('meeting.update', { id: meeting.id, status: 'finalizing' }, meeting.version).then(function () { const prompt = '会议 ' + meeting.id + ' 已结束，请调用 flowboard_snapshot 后使用 flowboard_finalize_meeting 完成整理。'; props.inputActions.setDraft(prompt); props.inputActions.submit() }) } }, '停止')) }
    slots.inject('conversation.view', function () { return slots.register({ name: 'conversation.view', id: 'flowboard-dynamic', order: 21, label: 'Flowboard 动态' }, App) })
    slots.inject('conversation.input.dock', function () { return slots.register({ name: 'conversation.input.dock', id: 'flowboard-dynamic-meeting', order: 31, label: 'Flowboard 会议' }, Dock) })
  },
}
