return {
  inject: ['shell', 'timer', 'agents', 'systemPrompt'],
  apply(ctx) {
    const shell = ctx.get('shell')
    if (shell === undefined) throw new Error('Flowboard dynamic Host requires the shell service')
    const disposers = []
    const apiRoot = '${FLOWBOARD_API_BASE:-http://127.0.0.1:8787}'

    function quote(value) { return "'" + String(value).replace(/'/g, "'\\''") + "'" }
    async function run(command, stdin) {
      const result = await shell.run(shell.resolve({ command: command, stdin: stdin, stdoutMaxBytes: 24 * 1024 * 1024 }))
      const output = result.stdout && result.stdout.text ? result.stdout.text : ''
      if (result.exitCode !== 0) throw new Error((result.stderr && result.stderr.text) || output || 'Flowboard command failed')
      return output
    }
    async function api(method, path, body) {
      const command = 'curl -fsS -X ' + method + ' -H "Authorization: Bearer ${FLOWBOARD_TOKEN:?FLOWBOARD_TOKEN is required}" -H "Content-Type: application/json" ' + (body === undefined ? '' : '--data-binary @- ') + '"' + apiRoot + path + '"'
      const output = await run(command, body === undefined ? undefined : JSON.stringify(body))
      try { return JSON.parse(output) } catch (error) { throw new Error('Flowboard returned invalid JSON: ' + output.slice(0, 200)) }
    }
    function queryPath(args) {
      const pairs = []
      if (args && args.projectId) pairs.push('projectId=' + encodeURIComponent(String(args.projectId)))
      if (args && args.meetingId) pairs.push('meetingId=' + encodeURIComponent(String(args.meetingId)))
      return '/v1/snapshot' + (pairs.length ? '?' + pairs.join('&') : '')
    }
    function handle(name, fn) { disposers.push(harness.handle(name, fn)) }
    handle('summary', function () { return api('GET', '/v1/summary') })
    handle('snapshot', function (args) { return api('GET', queryPath(args || {})) })
    handle('command', function (args) { return api('POST', '/v1/commands', args || {}) })
    handle('transcribeSegment', async function (args) {
      const base64 = String(args && args.base64 || '')
      const meetingId = String(args && args.meetingId || '')
      const clientSegmentId = String(args && args.clientSegmentId || '')
      if (!base64 || !meetingId || !clientSegmentId) throw new Error('meetingId, clientSegmentId and base64 are required')
      const padding = base64.endsWith('==') ? 2 : base64.endsWith('=') ? 1 : 0
      const size = Math.max(1, Math.floor(base64.length * 3 / 4) - padding)
      const contentType = String(args.contentType || 'audio/webm').split(';', 1)[0].trim().toLowerCase()
      const ticket = await api('POST', '/v1/uploads/tickets', { meetingId: meetingId, clientSegmentId: clientSegmentId, contentType: contentType, size: size, startedAt: args.startedAt, endedAt: args.endedAt })
      const upload = await run('base64 -d | curl -fsS -X PUT -H ' + quote('content-type: ' + contentType) + ' --data-binary @- ' + quote(ticket.uploadUrl), base64)
      const accepted = JSON.parse(upload)
      return { jobId: accepted.jobId, state: 'pending', text: null }
    })
    handle('transcription', function (args) {
      const jobId = String(args && args.jobId || '')
      if (!jobId) throw new Error('jobId is required')
      return api('GET', '/v1/transcriptions/' + encodeURIComponent(jobId))
    })

    const output = { schema: { type: 'object', additionalProperties: true, properties: {} }, render: function (_args, value) { return [{ type: 'text', text: JSON.stringify(value) }] } }
    function tool(spec) { const value = harness.defineTool({ name: spec.name, description: spec.description, parameters: spec.parameters, output: output, execute: spec.execute }); disposers.push(harness.registerTool(ctx, value)) }
    function key(exec, operation) { return 'tool:' + String(exec.callId) + ':' + operation }
    async function scope(projectId, teamId) { const snapshot = await api('GET', '/v1/snapshot'); const project = projectId ? snapshot.projects.find(function (item) { return item.id === projectId && item.role !== 'viewer' }) : snapshot.projects.find(function (item) { return item.role !== 'viewer' && (!teamId || item.teamId === teamId) }); const team = teamId ? snapshot.teams.find(function (item) { return item.id === teamId && item.role !== 'viewer' }) : snapshot.teams.find(function (item) { return item.id === (project && project.teamId) }) || snapshot.teams.find(function (item) { return item.role !== 'viewer' }); return { snapshot: snapshot, project: project, team: team } }
    function temporaryKey(callId) { const suffix = String(callId).replace(/[^a-z0-9]/gi, '').toUpperCase().slice(-7); return ('TMP' + (suffix || 'PROJECT')).slice(0, 12) }
    tool({ name: 'flowboard_snapshot', description: '读取 Flowboard 摘要，指定项目或会议时读取完整详情。', parameters: { project_id: { type: 'string' }, meeting_id: { type: 'string' } }, execute: function (args) { return args.project_id || args.meeting_id ? api('GET', queryPath({ projectId: args.project_id, meetingId: args.meeting_id })) : api('GET', '/v1/summary') } })
    tool({ name: 'flowboard_create_project', description: '立即创建项目；缺失非关键字段时使用临时值，后续再修订。', parameters: { team_id: { type: 'string' }, key: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, color: { type: 'string' } }, execute: async function (args, exec) { const current = await scope(undefined, args.team_id); if (!current.team) throw new Error('没有可写团队，无法创建项目'); const payload = { teamId: current.team.id, key: args.key || temporaryKey(exec.callId), name: args.name || '未命名项目' }; if (args.description !== undefined) payload.description = args.description; if (args.color !== undefined) payload.color = args.color; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'project.create'), type: 'project.create', payload: payload }) } })
    tool({ name: 'flowboard_update_project', description: '使用版本号修订项目临时字段。', parameters: { id: { type: 'string', required: true }, expected_version: { type: 'integer', required: true }, key: { type: 'string' }, name: { type: 'string' }, description: { type: 'string' }, color: { type: 'string' } }, execute: function (args, exec) { const payload = { id: args.id }; ['key', 'name', 'description', 'color'].forEach(function (field) { if (args[field] !== undefined) payload[field] = args[field] }); return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'project.update'), type: 'project.update', expectedVersion: args.expected_version, payload: payload }) } })
    tool({ name: 'flowboard_observe_meeting', description: '读取会议完整转录、Supervisor 水位和意图账本。', parameters: { meeting_id: { type: 'string', required: true } }, execute: function (args) { return api('GET', queryPath({ meetingId: args.meeting_id })) } })
    tool({ name: 'flowboard_ack_meeting', description: '确认 Supervisor 已分析到指定转录序号。', parameters: { meeting_id: { type: 'string', required: true }, analyzed_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.agent.progress'), type: 'meeting.agent.progress', payload: { id: args.meeting_id, analyzedSequence: args.analyzed_sequence } }) } })
    tool({ name: 'flowboard_upsert_meeting_intent', description: '按稳定键新建或修订会议意图，发言纠正时更新同一键。', parameters: { meeting_id: { type: 'string', required: true }, intent_key: { type: 'string', required: true }, kind: { type: 'string', enum: ['task', 'document', 'decision', 'risk', 'note'], required: true }, title: { type: 'string', required: true }, origin: { type: 'string', enum: ['user', 'assistant'] }, question: { type: 'string' }, summary: { type: 'string' }, content: { type: 'string' }, project_id: { type: 'string' }, project_ids: { type: 'array', items: { type: 'string' } }, assignee_id: { type: 'string' }, due_at: { type: 'string' }, priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] }, evidence_from_sequence: { type: 'integer', required: true }, evidence_to_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { const payload = { title: args.title }; if (args.origin !== undefined) payload.origin = args.origin; if (args.question !== undefined) payload.question = args.question; if (args.summary !== undefined) payload.summary = args.summary; if (args.content !== undefined) payload.content = args.content; if (args.project_id !== undefined) payload.projectId = args.project_id; if (args.project_ids !== undefined) payload.projectIds = args.project_ids; if (args.assignee_id !== undefined) payload.assigneeId = args.assignee_id; if (args.due_at !== undefined) payload.dueAt = args.due_at; if (args.priority !== undefined) payload.priority = args.priority; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.upsert'), type: 'meeting.intent.upsert', payload: { meetingId: args.meeting_id, intentKey: args.intent_key, kind: args.kind, payload: payload, evidenceFromSequence: args.evidence_from_sequence, evidenceToSequence: args.evidence_to_sequence } }) } })
    tool({ name: 'flowboard_raise_meeting_question', description: 'AI 提出问题并写入 assistant 来源的澄清意图。', parameters: { meeting_id: { type: 'string', required: true }, intent_key: { type: 'string', required: true }, question: { type: 'string', required: true }, project_id: { type: 'string' }, evidence_from_sequence: { type: 'integer', required: true }, evidence_to_sequence: { type: 'integer', required: true } }, execute: async function (args, exec) { const payload = { title: args.question, origin: 'assistant', question: args.question }; if (args.project_id) payload.projectId = args.project_id; const created = await api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.question.upsert'), type: 'meeting.intent.upsert', payload: { meetingId: args.meeting_id, intentKey: args.intent_key, kind: 'note', payload: payload, evidenceFromSequence: args.evidence_from_sequence, evidenceToSequence: args.evidence_to_sequence } }); return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.question.clarifying'), type: 'meeting.intent.status', payload: { id: created.entityId, revision: created.version, status: 'clarifying' } }) } })
    tool({ name: 'flowboard_reply_in_meeting', description: 'AI 给出简洁回复、提醒或建议，并写入会议的 AI 回复与提问列表。', parameters: { meeting_id: { type: 'string', required: true }, reply: { type: 'string', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.action:note'), type: 'meeting.action.append', payload: { id: args.meeting_id, callId: String(exec.callId), kind: 'note', summary: args.reply } }) } })
    tool({ name: 'flowboard_set_meeting_intent_status', description: '推进会议意图状态并可关联 continuable Subagent。', parameters: { intent_id: { type: 'string', required: true }, revision: { type: 'integer', required: true }, status: { type: 'string', enum: ['clarifying', 'approved', 'executing', 'superseded', 'rejected', 'failed'], required: true }, subagent_id: { type: 'string' }, error: { type: 'string' } }, execute: function (args, exec) { const payload = { id: args.intent_id, revision: args.revision, status: args.status }; if (args.subagent_id !== undefined) payload.subagentId = args.subagent_id; if (args.error !== undefined) payload.error = args.error; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.status'), type: 'meeting.intent.status', payload: payload }) } })
    tool({ name: 'flowboard_commit_meeting_intent', description: '使用意图修订和最新完整转录序号原子提交意图。', parameters: { intent_id: { type: 'string', required: true }, revision: { type: 'integer', required: true }, basis_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.commit'), type: 'meeting.intent.commit', payload: { id: args.intent_id, revision: args.revision, basisSequence: args.basis_sequence } }) } })
    tool({ name: 'flowboard_create_task', description: '立即创建任务；缺失项目或标题时推断范围并使用临时标题。', parameters: { project_id: { type: 'string' }, title: { type: 'string' }, summary: { type: 'string' }, assignee_id: { type: 'string' }, due_at: { type: 'string' }, priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] }, meeting_id: { type: 'string' } }, execute: async function (args, exec) { const current = await scope(args.project_id); if (!current.project) throw new Error('没有可写项目，无法创建任务'); const title = args.title || '未命名任务'; const payload = { projectId: current.project.id, title: title }; if (args.summary !== undefined) payload.summary = args.summary; if (args.assignee_id !== undefined) payload.assigneeId = args.assignee_id; if (args.due_at !== undefined) payload.dueAt = args.due_at; if (args.priority !== undefined) payload.priority = args.priority; if (args.meeting_id !== undefined) payload.meetingIds = [args.meeting_id]; const result = await api('POST', '/v1/commands', { idempotencyKey: key(exec, 'task.create'), type: 'task.create', payload: payload }); if (args.meeting_id) await api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.action:task'), type: 'meeting.action.append', payload: { id: args.meeting_id, callId: String(exec.callId), kind: 'task', summary: '创建任务：' + title, entityType: result.entityType, entityId: result.entityId } }); return result } })
    tool({ name: 'flowboard_update_meeting', description: '使用版本号修订即时会议的标题或总结。', parameters: { id: { type: 'string', required: true }, expected_version: { type: 'integer', required: true }, title: { type: 'string' }, summary: { type: 'string' }, decisions: { type: 'array', items: { type: 'string' } }, risks: { type: 'array', items: { type: 'string' } } }, execute: function (args, exec) { const payload = { id: args.id }; ['title', 'summary', 'decisions', 'risks'].forEach(function (field) { if (args[field] !== undefined) payload[field] = args[field] }); return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.update'), type: 'meeting.update', expectedVersion: args.expected_version, payload: payload }) } })
    tool({ name: 'flowboard_create_document', description: '立即创建空白或完整资料；缺失范围或标题时推断并使用临时值。', parameters: { team_id: { type: 'string' }, project_ids: { type: 'array', items: { type: 'string' } }, title: { type: 'string' }, content: { type: 'string' }, meeting_id: { type: 'string' } }, execute: async function (args, exec) { const current = await scope(args.project_ids && args.project_ids[0], args.team_id); const projectIds = args.project_ids || (current.project ? [current.project.id] : []); if (!current.team || !projectIds.length) throw new Error('没有可写项目，无法创建资料'); const payload = { teamId: current.team.id, projectIds: projectIds, type: 'doc', title: args.title || '未命名资料', content: args.content || '' }; if (args.meeting_id) payload.sourceMeetingId = args.meeting_id; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'library.create'), type: 'library.create', payload: payload }) } })
    tool({ name: 'flowboard_finalize_meeting', description: '所有转录和意图收敛后写入最终总结并结束会议。', parameters: { meeting_id: { type: 'string', required: true }, expected_version: { type: 'integer', required: true }, summary: { type: 'string', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.finalize'), type: 'meeting.finalize', expectedVersion: args.expected_version, payload: { id: args.meeting_id, summary: args.summary } }) } })

    const agents = ctx.get('agents'); const systemPrompt = ctx.get('systemPrompt'); const meetingSnapshots = new Map(); const pendingMessages = new Map(); const attached = new Set(); const finalizationNotified = new Set(); let coordinatorStopped = false; let coordinatorTimer = null; let coordinatorBusy = false
    function agentMessage(text) { return Object.freeze({ id: crypto.randomUUID(), role: 'user', content: [Object.freeze({ type: 'text', text: text })], source: Object.freeze({ kind: 'plugin', plugin: '@flowboard/dynamic', form: 'meeting-supervisor' }) }) }
    function notifyAgent(agent, meetingId, text) { const next = agentMessage(text); const previous = pendingMessages.get(meetingId); if (previous && agent.inbox.replace(previous, next)) { pendingMessages.set(meetingId, next.id); return } pendingMessages.set(meetingId, next.id); if (agent.status === 'running') agent.steer(next); else agent.followup(next) }
    function renderMeetingContext(snapshot) { const meeting = snapshot.meetings[0]; if (!meeting) return ''; const binding = snapshot.meetingAgentBindings.find(function (item) { return item.meetingId === meeting.id }); const transcript = snapshot.utterances.map(function (item) { return '[' + item.sequence + '] ' + item.text }).join('\n') || '（暂无转录）'; const intents = snapshot.meetingIntents.map(function (item) { return '- ' + item.id + ' r' + item.revision + ' [' + item.status + '/' + item.kind + '/' + (item.payload.origin || 'user') + '] ' + item.payload.title }).join('\n') || '- 无'; return '# Flowboard 会议 Supervisor\n会议：' + meeting.title + ' (' + meeting.id + ')，状态=' + meeting.status + '，自动化=' + meeting.settings.automation + '\n水位：delivered=' + (binding ? binding.deliveredSequence : 0) + '，analyzed=' + (binding ? binding.analyzedSequence : 0) + '\n始终基于完整转录更新稳定意图；安全可逆操作先创建后修订。创建项目必须直接调用 flowboard_create_project，绝不能创建“新建项目”任务。提问调用 flowboard_raise_meeting_question，主动回复或提醒调用 flowboard_reply_in_meeting。\n当前意图：\n' + intents + '\n完整转录：\n' + transcript }
    if (systemPrompt) { disposers.push(systemPrompt.context({ name: 'flowboard:act-first', order: 210, text: 'Flowboard 中安全可逆的项目、任务、资料等创建操作要先执行。非关键字段缺失时使用未命名或空值创建，后续读取 version 修订；只有权限、无可写范围、删除或不可逆操作才停下询问。' })); disposers.push(systemPrompt.context({ name: 'flowboard:meeting-supervisor', order: 220, text: function (context) { return context.agent ? renderMeetingContext(meetingSnapshots.get(String(context.agent.id)) || { meetings: [] }) : '' } })) }
    async function coordinatorTick() { if (coordinatorStopped || coordinatorBusy || !agents) return; coordinatorBusy = true; try { const workspace = await api('GET', '/v1/snapshot'); const active = (workspace.meetingAgentBindings || []).filter(function (item) { return item.state === 'active' }); for (const binding of active) { const agent = agents.get(binding.sessionId); if (!agent) continue; const detail = await api('GET', queryPath({ meetingId: binding.meetingId })); meetingSnapshots.set(binding.sessionId, detail); const meeting = detail.meetings[0]; const latest = detail.utterances.length ? detail.utterances[detail.utterances.length - 1].sequence : 0; if (latest > binding.deliveredSequence) { const fresh = detail.utterances.filter(function (item) { return item.sequence > binding.deliveredSequence }).map(function (item) { return '[' + item.sequence + '] ' + item.text }).join('\n'); await api('POST', '/v1/commands', { idempotencyKey: 'dynamic-coordinator:deliver:' + binding.meetingId + ':' + latest, type: 'meeting.agent.progress', payload: { id: binding.meetingId, deliveredSequence: latest } }); notifyAgent(agent, binding.meetingId, '会议有新转录：\n' + fresh + '\n结合完整上下文修订意图，完成后调用 flowboard_ack_meeting。') } if (meeting && meeting.status === 'finalizing' && !finalizationNotified.has(meeting.id)) { finalizationNotified.add(meeting.id); notifyAgent(agent, meeting.id, '会议已停止采集。处理完全部转录和意图后调用 flowboard_finalize_meeting。') } if (!attached.has(agent.id)) { attached.add(agent.id); agent.ctx.on('agent/turn-stopping', async function () { const current = await api('GET', queryPath({ meetingId: binding.meetingId })); meetingSnapshots.set(binding.sessionId, current); const progress = current.meetingAgentBindings.find(function (item) { return item.sessionId === binding.sessionId && item.state === 'active' }); if (progress && progress.deliveredSequence > progress.analyzedSequence) agent.steer(agentMessage('仍有转录未确认，请继续分析并调用 flowboard_ack_meeting。')) }) } } } catch (error) { ctx.logger.warn('Flowboard dynamic coordinator: ' + String(error && error.message || error)) } finally { coordinatorBusy = false; if (!coordinatorStopped) coordinatorTimer = ctx.timer.timeout(coordinatorTick, 1000) } }
    coordinatorTick()
    ctx.effect(function () { return function () { coordinatorStopped = true; if (coordinatorTimer) coordinatorTimer(); disposers.forEach(function (dispose) { try { dispose() } catch (error) {} }) } })
  },
}
