return {
  inject: ['shell', 'timer', 'agents', 'systemPrompt'],
  apply(ctx) {
    const shell = ctx.get('shell')
    if (shell === undefined) throw new Error('Flowboard dynamic Host requires the shell service')
    const disposers = []
    const apiRoot = '${FLOWBOARD_API_BASE:-http://127.0.0.1:8787}'

    function quote(value) { return "'" + String(value).replace(/'/g, "'\\''") + "'" }
    async function run(command, stdin) {
      const result = await shell.run(shell.resolve({ command: command, stdin: stdin, stdoutMaxBytes: 24 * 1024 * 1024 }))
      const output = result.stdout && result.stdout.text ? result.stdout.text : ''
      if (result.exitCode !== 0) throw new Error((result.stderr && result.stderr.text) || output || 'Flowboard command failed')
      return output
    }
    async function api(method, path, body) {
      const command = 'curl -fsS -X ' + method + ' -H "Authorization: Bearer ${FLOWBOARD_TOKEN:?FLOWBOARD_TOKEN is required}" -H "Content-Type: application/json" ' + (body === undefined ? '' : '--data-binary @- ') + '"' + apiRoot + path + '"'
      const output = await run(command, body === undefined ? undefined : JSON.stringify(body))
      try { return JSON.parse(output) } catch (error) { throw new Error('Flowboard returned invalid JSON: ' + output.slice(0, 200)) }
    }
    function queryPath(args) {
      const pairs = []
      if (args && args.projectId) pairs.push('projectId=' + encodeURIComponent(String(args.projectId)))
      if (args && args.meetingId) pairs.push('meetingId=' + encodeURIComponent(String(args.meetingId)))
      return '/v1/snapshot' + (pairs.length ? '?' + pairs.join('&') : '')
    }
    function handle(name, fn) { disposers.push(harness.handle(name, fn)) }
    handle('summary', function () { return api('GET', '/v1/summary') })
    handle('snapshot', function (args) { return api('GET', queryPath(args || {})) })
    handle('command', function (args) { return api('POST', '/v1/commands', args || {}) })
    handle('transcribeSegment', async function (args) {
      const base64 = String(args && args.base64 || '')
      const meetingId = String(args && args.meetingId || '')
      const clientSegmentId = String(args && args.clientSegmentId || '')
      if (!base64 || !meetingId || !clientSegmentId) throw new Error('meetingId, clientSegmentId and base64 are required')
      const padding = base64.endsWith('==') ? 2 : base64.endsWith('=') ? 1 : 0
      const size = Math.max(1, Math.floor(base64.length * 3 / 4) - padding)
      const contentType = String(args.contentType || 'audio/webm').split(';', 1)[0].trim().toLowerCase()
      const ticket = await api('POST', '/v1/uploads/tickets', { meetingId: meetingId, clientSegmentId: clientSegmentId, contentType: contentType, size: size, startedAt: args.startedAt, endedAt: args.endedAt })
      const upload = await run('base64 -d | curl -fsS -X PUT -H ' + quote('content-type: ' + contentType) + ' --data-binary @- ' + quote(ticket.uploadUrl), base64)
      const accepted = JSON.parse(upload)
      return { jobId: accepted.jobId, state: 'pending', text: null }
    })
    handle('transcription', function (args) {
      const jobId = String(args && args.jobId || '')
      if (!jobId) throw new Error('jobId is required')
      return api('GET', '/v1/transcriptions/' + encodeURIComponent(jobId))
    })

    const output = { schema: { type: 'object', additionalProperties: true, properties: {} }, render: function (_args, value) { return [{ type: 'text', text: JSON.stringify(value) }] } }
    function tool(spec) { const value = harness.defineTool({ name: spec.name, description: spec.description, parameters: spec.parameters, output: output, execute: spec.execute }); disposers.push(harness.registerTool(ctx, value)) }
    function key(exec, operation) { return 'tool:' + String(exec.callId) + ':' + operation }
    tool({ name: 'flowboard_snapshot', description: '读取 Flowboard 摘要，指定项目或会议时读取完整详情。', parameters: { project_id: { type: 'string' }, meeting_id: { type: 'string' } }, execute: function (args) { return args.project_id || args.meeting_id ? api('GET', queryPath({ projectId: args.project_id, meetingId: args.meeting_id })) : api('GET', '/v1/summary') } })
    tool({ name: 'flowboard_observe_meeting', description: '读取会议完整转录、Supervisor 水位和意图账本。', parameters: { meeting_id: { type: 'string', required: true } }, execute: function (args) { return api('GET', queryPath({ meetingId: args.meeting_id })) } })
    tool({ name: 'flowboard_ack_meeting', description: '确认 Supervisor 已分析到指定转录序号。', parameters: { meeting_id: { type: 'string', required: true }, analyzed_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.agent.progress'), type: 'meeting.agent.progress', payload: { id: args.meeting_id, analyzedSequence: args.analyzed_sequence } }) } })
    tool({ name: 'flowboard_upsert_meeting_intent', description: '按稳定键新建或修订会议意图，发言纠正时更新同一键。', parameters: { meeting_id: { type: 'string', required: true }, intent_key: { type: 'string', required: true }, kind: { type: 'string', enum: ['task', 'document', 'decision', 'risk', 'note'], required: true }, title: { type: 'string', required: true }, summary: { type: 'string' }, content: { type: 'string' }, project_id: { type: 'string' }, project_ids: { type: 'array', items: { type: 'string' } }, assignee_id: { type: 'string' }, due_at: { type: 'string' }, priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] }, evidence_from_sequence: { type: 'integer', required: true }, evidence_to_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { const payload = { title: args.title }; if (args.summary !== undefined) payload.summary = args.summary; if (args.content !== undefined) payload.content = args.content; if (args.project_id !== undefined) payload.projectId = args.project_id; if (args.project_ids !== undefined) payload.projectIds = args.project_ids; if (args.assignee_id !== undefined) payload.assigneeId = args.assignee_id; if (args.due_at !== undefined) payload.dueAt = args.due_at; if (args.priority !== undefined) payload.priority = args.priority; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.upsert'), type: 'meeting.intent.upsert', payload: { meetingId: args.meeting_id, intentKey: args.intent_key, kind: args.kind, payload: payload, evidenceFromSequence: args.evidence_from_sequence, evidenceToSequence: args.evidence_to_sequence } }) } })
    tool({ name: 'flowboard_set_meeting_intent_status', description: '推进会议意图状态并可关联 continuable Subagent。', parameters: { intent_id: { type: 'string', required: true }, revision: { type: 'integer', required: true }, status: { type: 'string', enum: ['clarifying', 'approved', 'executing', 'superseded', 'rejected', 'failed'], required: true }, subagent_id: { type: 'string' }, error: { type: 'string' } }, execute: function (args, exec) { const payload = { id: args.intent_id, revision: args.revision, status: args.status }; if (args.subagent_id !== undefined) payload.subagentId = args.subagent_id; if (args.error !== undefined) payload.error = args.error; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.status'), type: 'meeting.intent.status', payload: payload }) } })
    tool({ name: 'flowboard_commit_meeting_intent', description: '使用意图修订和最新完整转录序号原子提交意图。', parameters: { intent_id: { type: 'string', required: true }, revision: { type: 'integer', required: true }, basis_sequence: { type: 'integer', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.intent.commit'), type: 'meeting.intent.commit', payload: { id: args.intent_id, revision: args.revision, basisSequence: args.basis_sequence } }) } })
    tool({ name: 'flowboard_create_task', description: '在项目中创建任务，并可关联当前会议。', parameters: { project_id: { type: 'string', required: true }, title: { type: 'string', required: true }, summary: { type: 'string' }, assignee_id: { type: 'string' }, due_at: { type: 'string' }, priority: { type: 'string', enum: ['low', 'medium', 'high', 'urgent'] }, meeting_id: { type: 'string' } }, execute: async function (args, exec) { const payload = { projectId: args.project_id, title: args.title }; if (args.summary !== undefined) payload.summary = args.summary; if (args.assignee_id !== undefined) payload.assigneeId = args.assignee_id; if (args.due_at !== undefined) payload.dueAt = args.due_at; if (args.priority !== undefined) payload.priority = args.priority; if (args.meeting_id !== undefined) payload.meetingIds = [args.meeting_id]; const result = await api('POST', '/v1/commands', { idempotencyKey: key(exec, 'task.create'), type: 'task.create', payload: payload }); if (args.meeting_id) await api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.action:task'), type: 'meeting.action.append', payload: { id: args.meeting_id, callId: String(exec.callId), kind: 'task', summary: '创建任务：' + args.title, entityType: result.entityType, entityId: result.entityId } }); return result } })
    tool({ name: 'flowboard_create_document', description: '创建项目或会议资料。', parameters: { team_id: { type: 'string', required: true }, project_ids: { type: 'array', items: { type: 'string' }, required: true }, title: { type: 'string', required: true }, content: { type: 'string', required: true }, meeting_id: { type: 'string' } }, execute: async function (args, exec) { const payload = { teamId: args.team_id, projectIds: args.project_ids, type: 'doc', title: args.title, content: args.content }; if (args.meeting_id) payload.sourceMeetingId = args.meeting_id; return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'library.create'), type: 'library.create', payload: payload }) } })
    tool({ name: 'flowboard_finalize_meeting', description: '所有转录和意图收敛后写入最终总结并结束会议。', parameters: { meeting_id: { type: 'string', required: true }, expected_version: { type: 'integer', required: true }, summary: { type: 'string', required: true } }, execute: function (args, exec) { return api('POST', '/v1/commands', { idempotencyKey: key(exec, 'meeting.finalize'), type: 'meeting.finalize', expectedVersion: args.expected_version, payload: { id: args.meeting_id, summary: args.summary } }) } })

    const agents = ctx.get('agents'); const systemPrompt = ctx.get('systemPrompt'); const meetingSnapshots = new Map(); const pendingMessages = new Map(); const attached = new Set(); const finalizationNotified = new Set(); let coordinatorStopped = false; let coordinatorTimer = null; let coordinatorBusy = false
    function agentMessage(text) { return Object.freeze({ id: crypto.randomUUID(), role: 'user', content: [Object.freeze({ type: 'text', text: text })], source: Object.freeze({ kind: 'plugin', plugin: '@flowboard/dynamic', form: 'meeting-supervisor' }) }) }
    function notifyAgent(agent, meetingId, text) { const next = agentMessage(text); const previous = pendingMessages.get(meetingId); if (previous && agent.inbox.replace(previous, next)) { pendingMessages.set(meetingId, next.id); return } pendingMessages.set(meetingId, next.id); if (agent.status === 'running') agent.steer(next); else agent.followup(next) }
    function renderMeetingContext(snapshot) { const meeting = snapshot.meetings[0]; if (!meeting) return ''; const binding = snapshot.meetingAgentBindings.find(function (item) { return item.meetingId === meeting.id }); const transcript = snapshot.utterances.map(function (item) { return '[' + item.sequence + '] ' + item.text }).join('\n') || '（暂无转录）'; const intents = snapshot.meetingIntents.map(function (item) { return '- ' + item.id + ' r' + item.revision + ' [' + item.status + '/' + item.kind + '] ' + item.payload.title }).join('\n') || '- 无'; return '# Flowboard 会议 Supervisor\n会议：' + meeting.title + ' (' + meeting.id + ')，状态=' + meeting.status + '，自动化=' + meeting.settings.automation + '\n水位：delivered=' + (binding ? binding.deliveredSequence : 0) + '，analyzed=' + (binding ? binding.analyzedSequence : 0) + '\n始终基于完整转录更新稳定意图；更正覆盖旧意图；写入前校验 revision 与最新 sequence；复杂工作可派发 continuable Subagent。\n当前意图：\n' + intents + '\n完整转录：\n' + transcript }
    if (systemPrompt) disposers.push(systemPrompt.context({ name: 'flowboard:meeting-supervisor', order: 220, text: function (context) { return context.agent ? renderMeetingContext(meetingSnapshots.get(String(context.agent.id)) || { meetings: [] }) : '' } }))
    async function coordinatorTick() { if (coordinatorStopped || coordinatorBusy || !agents) return; coordinatorBusy = true; try { const workspace = await api('GET', '/v1/snapshot'); const active = (workspace.meetingAgentBindings || []).filter(function (item) { return item.state === 'active' }); for (const binding of active) { const agent = agents.get(binding.sessionId); if (!agent) continue; const detail = await api('GET', queryPath({ meetingId: binding.meetingId })); meetingSnapshots.set(binding.sessionId, detail); const meeting = detail.meetings[0]; const latest = detail.utterances.length ? detail.utterances[detail.utterances.length - 1].sequence : 0; if (latest > binding.deliveredSequence) { const fresh = detail.utterances.filter(function (item) { return item.sequence > binding.deliveredSequence }).map(function (item) { return '[' + item.sequence + '] ' + item.text }).join('\n'); await api('POST', '/v1/commands', { idempotencyKey: 'dynamic-coordinator:deliver:' + binding.meetingId + ':' + latest, type: 'meeting.agent.progress', payload: { id: binding.meetingId, deliveredSequence: latest } }); notifyAgent(agent, binding.meetingId, '会议有新转录：\n' + fresh + '\n结合完整上下文修订意图，完成后调用 flowboard_ack_meeting。') } if (meeting && meeting.status === 'finalizing' && !finalizationNotified.has(meeting.id)) { finalizationNotified.add(meeting.id); notifyAgent(agent, meeting.id, '会议已停止采集。处理完全部转录和意图后调用 flowboard_finalize_meeting。') } if (!attached.has(agent.id)) { attached.add(agent.id); agent.ctx.on('agent/turn-stopping', async function () { const current = await api('GET', queryPath({ meetingId: binding.meetingId })); meetingSnapshots.set(binding.sessionId, current); const progress = current.meetingAgentBindings.find(function (item) { return item.sessionId === binding.sessionId && item.state === 'active' }); if (progress && progress.deliveredSequence > progress.analyzedSequence) agent.steer(agentMessage('仍有转录未确认，请继续分析并调用 flowboard_ack_meeting。')) }) } } } catch (error) { ctx.logger.warn('Flowboard dynamic coordinator: ' + String(error && error.message || error)) } finally { coordinatorBusy = false; if (!coordinatorStopped) coordinatorTimer = ctx.timer.timeout(coordinatorTick, 1000) } }
    coordinatorTick()
    ctx.effect(function () { return function () { coordinatorStopped = true; if (coordinatorTimer) coordinatorTimer(); disposers.forEach(function (dispose) { try { dispose() } catch (error) {} }) } })
  },
}
