import { useMemo, useState } from 'react'
import { Button, IconEditOutline16, IconPlusOutline16, IconSearchOutline16, IconTrashOutline16, Input } from '@deepseek-ai/dsh-client-ui-primitives'
import type { FlowboardSnapshot, Priority, TaskView } from '@flowboard/contracts'
import { ConfirmDialog, Empty, EntityModal, Field, IconButton, PageHeader, formatDate, localDateTime, toIso, type CommandHandler } from './shared.tsx'
import css from '../flowboard.module.css'

type TaskDialog = { type: 'create' } | { type: 'edit' | 'delete'; task: TaskView } | null
const priorityText: Record<Priority, string> = { low: '低', medium: '中', high: '高', urgent: '紧急' }

export function BoardView({ snapshot, projectId, command, mode = 'board', personal = false }: { snapshot: FlowboardSnapshot; projectId: string | null; command: CommandHandler; mode?: 'board' | 'table'; personal?: boolean }) {
  const [dialog, setDialog] = useState<TaskDialog>(null)
  const [query, setQuery] = useState('')
  const projectIds = new Set(snapshot.projects.map(project => project.id))
  const tasks = useMemo(() => snapshot.tasks.filter(task => (personal ? task.assigneeId === snapshot.actor.id : task.projectId === projectId) && `${task.title} ${task.summary}`.toLowerCase().includes(query.trim().toLowerCase())), [personal, projectId, query, snapshot.actor.id, snapshot.tasks])
  const activeProjectId = projectId ?? (personal ? snapshot.projects[0]?.id ?? null : null)
  if (activeProjectId === null && !personal) return <Empty title="请先创建项目" detail="任务看板需要归属到一个项目。" />
  const statuses = snapshot.workflowStatuses.filter(status => personal ? projectIds.has(status.projectId) : status.projectId === activeProjectId).sort((a, b) => a.position - b.position)
  const submitTask = async (data: FormData, task?: TaskView) => {
    const selectedProject = task?.projectId ?? String(data.get('projectId') || activeProjectId)
    const dueAt = toIso(data.get('dueAt')); const assigneeId = String(data.get('assigneeId') ?? '')
    const payload = { title: String(data.get('title')), summary: String(data.get('summary') ?? ''), detail: String(data.get('detail') ?? ''), statusId: String(data.get('statusId')), priority: String(data.get('priority')) as Priority, progress: Number(data.get('progress')) / 100 }
    if (task === undefined) await command({ type: 'task.create', payload: { projectId: selectedProject, ...payload, ...(assigneeId === '' ? {} : { assigneeId }), ...(dueAt === undefined ? {} : { dueAt }) } })
    else await command({ type: 'task.update', expectedVersion: task.version, payload: { id: task.id, ...payload, assigneeId: assigneeId || null, dueAt: dueAt ?? null } })
  }
  const editor = dialog?.type === 'edit' ? dialog.task : undefined
  const taskCard = (task: TaskView) => {
    const assignee = snapshot.people.find(person => person.id === task.assigneeId)
    return <article className={css.task} key={task.id}><div className={css.taskTop}><span className={`${css.priority} ${css[`priority_${task.priority}`]}`}>{priorityText[task.priority]}</span><div className={css.rowActions}><IconButton label="编辑任务" onClick={() => setDialog({ type: 'edit', task })}><IconEditOutline16 /></IconButton><IconButton label="删除任务" onClick={() => setDialog({ type: 'delete', task })}><IconTrashOutline16 /></IconButton></div></div><strong>{task.title}</strong>{task.summary !== '' && <p>{task.summary}</p>}<div className={css.taskProgress}><i style={{ width: `${Math.round(task.progress * 100)}%` }} /></div><div className={css.taskMeta}><span>{assignee?.name ?? '未指派'}</span><span>{task.dueAt === null ? `${Math.round(task.progress * 100)}%` : formatDate(task.dueAt, false)}</span></div><select className={css.moveSelect} aria-label={`移动任务 ${task.title}`} value={task.statusId} onChange={event => void command({ type: 'task.update', expectedVersion: task.version, payload: { id: task.id, statusId: event.target.value } }).catch(() => undefined)}>{snapshot.workflowStatuses.filter(status => status.projectId === task.projectId).map(status => <option key={status.id} value={status.id}>{status.name}</option>)}</select></article>
  }
  return <section><PageHeader title={personal ? (mode === 'table' ? '我的任务' : '我的看板') : mode === 'table' ? '任务表' : '项目看板'} meta={`${tasks.length} 项工作`} actions={<><Input className={css.searchInput!} icon={<IconSearchOutline16 />} value={query} onChange={event => setQuery(event.target.value)} placeholder="搜索任务" aria-label="搜索任务" /><Button variant="primary" size="sm" icon={<IconPlusOutline16 />} disabled={activeProjectId === null} onClick={() => setDialog({ type: 'create' })}>新建任务</Button></>} />
    {mode === 'board' ? <div className={css.board}>{statuses.map(status => { const grouped = tasks.filter(task => task.statusId === status.id); return <section className={css.column} key={status.id}><header style={{ borderTopColor: status.color }}><h3>{status.name}</h3><span>{grouped.length}</span></header><div className={css.taskList}>{grouped.map(taskCard)}{grouped.length === 0 && <div className={css.columnEmpty}>暂无任务</div>}</div></section> })}</div> : <div className={css.taskTable}><div className={css.taskTableHead}><span>任务</span><span>项目</span><span>状态</span><span>负责人</span><span>截止</span></div>{tasks.map(task => { const project = snapshot.projects.find(item => item.id === task.projectId); const status = snapshot.workflowStatuses.find(item => item.id === task.statusId); return <button type="button" key={task.id} onClick={() => setDialog({ type: 'edit', task })}><strong>{project?.key}-{task.sequence} · {task.title}</strong><span>{project?.name}</span><span>{status?.name}</span><span>{snapshot.people.find(person => person.id === task.assigneeId)?.name ?? '未指派'}</span><span>{formatDate(task.dueAt, false)}</span></button> })}</div>}
    {tasks.length === 0 && <Empty title="没有符合条件的任务" />}
    {(dialog?.type === 'create' || dialog?.type === 'edit') && <EntityModal open title={editor === undefined ? '新建任务' : '编辑任务'} submitLabel={editor === undefined ? '创建' : '保存'} onClose={() => setDialog(null)} onSubmit={data => submitTask(data, editor)}><div className={css.formGrid}>{personal && editor === undefined && <Field label="所属项目"><select name="projectId" required defaultValue={activeProjectId ?? ''}>{snapshot.projects.map(project => <option key={project.id} value={project.id}>{project.name}</option>)}</select></Field>}<Field label="任务标题"><Input name="title" required autoFocus maxLength={240} defaultValue={editor?.title} /></Field><Field label="工作流状态"><select name="statusId" defaultValue={editor?.statusId ?? snapshot.workflowStatuses.find(status => status.projectId === (editor?.projectId ?? activeProjectId))?.id}>{snapshot.workflowStatuses.filter(status => status.projectId === (editor?.projectId ?? activeProjectId)).map(status => <option value={status.id} key={status.id}>{status.name}</option>)}</select></Field><Field label="负责人"><select name="assigneeId" defaultValue={editor?.assigneeId ?? ''}><option value="">未指派</option>{snapshot.people.map(person => <option key={person.id} value={person.id}>{person.name}</option>)}</select></Field><Field label="优先级"><select name="priority" defaultValue={editor?.priority ?? 'medium'}><option value="low">低</option><option value="medium">中</option><option value="high">高</option><option value="urgent">紧急</option></select></Field><Field label="完成进度"><input name="progress" type="number" min="0" max="100" step="5" defaultValue={Math.round((editor?.progress ?? 0) * 100)} /></Field><Field label="截止时间"><input name="dueAt" type="datetime-local" defaultValue={localDateTime(editor?.dueAt ?? null)} /></Field></div><Field label="摘要"><Input name="summary" maxLength={1000} defaultValue={editor?.summary} /></Field><Field label="详细说明"><textarea name="detail" rows={5} defaultValue={editor?.detail} /></Field></EntityModal>}
    {dialog?.type === 'delete' && <ConfirmDialog open title="删除任务" detail={`确定删除“${dialog.task.title}”吗？`} onClose={() => setDialog(null)} onConfirm={async () => command({ type: 'task.delete', expectedVersion: dialog.task.version, payload: { id: dialog.task.id } })} />}
  </section>
}
